# Trained with Tesla V100-SXM2(32GB) x 8 GPUs. It takes about 1.5 days.
batch_type: numel
batch_bins: 6000000
accum_grad: 1
max_epoch: 20
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    positionwise_layer_type: "spinal"
    use_cnn_module:  true
    cnn_module_kernel: 15
    se_type: noe"
    fused: True
    fused_num: 2

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.003
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

#frontend_conf:
#  n_fft: 512
#  hop_length: 128

# specaug: specaug
# specaug_conf:
#     apply_time_warp: false
# #    time_warp_window: 5
# #    time_warp_mode: bicubic
#     apply_freq_mask: true
#     freq_mask_width_range:
#     - 0
#     - 30
#     num_freq_mask: 2
#     apply_time_mask: true
#     time_mask_width_range:
#     - 0
#     - 100
#     num_time_mask: 2
