# Trained with Tesla V100-SXM2(32GB) x 8 GPUs. It takes about 1.5 days.
batch_type: numel
batch_bins: 10000000
accum_grad: 1
max_epoch: 100
patience: none
init: none
seed: 123
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: contextnet
encoder_conf:
    model_size: "small"
    output_size: 640
    num_layers: 5
    kernel_size: 5
    num_channels: 256
    dropout_rate: 0.0
    activation_type: "swish"
    conv_layer_type: "base"


decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 3
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.003
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

ctc_conf:
    ignore_nan_grad: true

#frontend_conf:
#  n_fft: 512
#  hop_length: 128

# specaug: specaug
# specaug_conf:
#     apply_time_warp: false
# #    time_warp_window: 5
# #    time_warp_mode: bicubic
#     apply_freq_mask: true
#     freq_mask_width_range:
#     - 0
#     - 30
#     num_freq_mask: 2
#     apply_time_mask: true
#     time_mask_width_range:
#     - 0
#     - 40
#     num_time_mask: 2
