# Trained with Tesla V100-SXM2(32GB) x 8 GPUs. It takes about 1.5 days.
batch_type: numel
batch_bins: 20000000
accum_grad: 1
max_epoch: 50
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: contextnet
encoder_conf:
    model_size: "medium"
    output_size: 512
    num_layers: 5
    kernel_size: 5
    num_channels: 256
    activation_type: "relu"
    conv_layer_type: "base"
    wshare: 4
    dropout_rate: 0.1


decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 640
    dropout: 0.0

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.05
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 10

#frontend_conf:
#  n_fft: 512
#  hop_length: 128

# specaug: specaug
# specaug_conf:
#     apply_time_warp: false
# #    time_warp_window: 5
# #    time_warp_mode: bicubic
#     apply_freq_mask: true
#     freq_mask_width_range:
#     - 0
#     - 30
#     num_freq_mask: 2
#     apply_time_mask: true
#     time_mask_width_range:
#     - 0
#     - 100
#     num_time_mask: 2
